---
- name: urotaxi application playbook
  hosts: all
  vars:
    TOMCAT_DOWNLOAD_URL: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.73/bin/apache-tomcat-9.0.73.tar.gz"
    TOMCAT_HOME_DIR: "/u01/middleware/apache-tomcat-9.0.73"
  tasks:
    - name: install jdk11
      apt:
        name: "openjdk-11-jdk"
        state: present
        update_cache: yes
      become: yes
      become_method: sudo
    - name: create middleware directory
      file:
        path: /u01/middleware
        state: directory
        owner: ubuntu
        group: ubuntu
      become: yes
      become_method: sudo
    - name: download tomcat9
      get_url: 
        url: "{{TOMCAT_DOWNLOAD_URL}}"
        dest: /u01/middleware
    - name: unzip tomcat
      unarchive:
        src: /u01/middleware/apache-tomcat-9.0.73.tar.gz
        dest: /u01/middleware
        remote_src: true
    - name: find jdk home
      shell: "readlink -f $(which java) | sed 's/bin.*//g'"        
      register: JDK_HOME
    - name: install tomcat as service
      template:
        src: tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
      become: yes
      become_method: sudo
      notify:
        - tomcatreload
    - name: install python3-pymysql
      apt:
        name: python3-pymysql
        state: present
        update_cache: yes
      become: yes
      become_method: sudo    
    - name: install mysql client
      apt:
        name: mysql-client-8.0
        state: present
        update_cache: yes
      become: yes
      become_method: sudo      
    - name: copy schema file
      copy:
        src: "{{ lookup('env','WORKSPACE') }}/src/main/db/urotaxidb.sql"
        dest: /tmp/ 
    - name: create schema
      community.mysql.mysql_db:
        state: import
        name: all   
        target: /tmp/urotaxidb.sql
        login_host : "{{ lookup('env','DB_HOST') }}"
        login_user : "{{ lookup('env','UROTAXI_DB_USER') }}"
        login_password: "{{ lookup('env','UROTAXI_DB_PSW') }}"
    - name: deploy
      copy:
        src: "{{ lookup('env','WORKSPACE') }}/target/urotaxi.war"
        dest: /u01/middleware/apache-tomcat-9.0.73/webapps/
      notify:
        - tomcatrestart
  handlers:
    - name: tomcatreload
      service:
        name: tomcat
        state: reloaded
        enabled: yes 
      become: yes
      become_method: sudo
    - name: tomcatrestart
      service:
        name: tomcat
        state: restarted
      become: yes
      become_method: sudo           

